name: Docker Build & Publish
env:
    IMAGENAME: robinmoser/doh-filter

on:
  push:
    branches:
      - main

jobs:

  release:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Setup buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build/Push - latest
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGENAME }}:latest
